service: gmail-archive

frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-plugin-aws-alerts
  - serverless-prune-plugin

provider:
  name: aws
  profile: bob
  region: ${env:region, 'us-east-1'}
  runtime: nodejs22.x
  logRetentionInDays: 60
  memorySize: 256
  timeout: 120
  environment:
    username: ${env:username}
    password: ${env:password}
    bucket: ${env:bucket}
    region: ${env:region, 'us-east-1'}
    NODE_OPTIONS: --enable-source-maps
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${env:bucket}/*"

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2 hours
      - schedule: rate(2 hours)

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${opt:stage, 'dev'}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:alert_email}
    alarms:
      - functionErrors
  prune:
    automatic: true
    number: 3
  esbuild:
    # magic to build ESM target for lambda
    # see https://github.com/evanw/esbuild/issues/1921#issuecomment-1152887672
    # NOTE: "serverless invoke local" won't work with generated handler.mjs yet :(
    # see https://github.com/serverless/serverless/issues/11308
    minify: true
    platform: node
    target: esnext
    sourcemap: true
    sourcesContent: false
    format: esm
    outExtension:
      .js: .mjs
    banner:
      js: import { createRequire } from 'module';const require = createRequire(import.meta.url);
